# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from scrapper.grpc import scrapper_pb2 as scrapper_dot_grpc_dot_scrapper__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in scrapper/grpc/scrapper_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScrapperServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScrapeNovels = channel.unary_stream(
                '/scrapper.ScrapperService/ScrapeNovels',
                request_serializer=scrapper_dot_grpc_dot_scrapper__pb2.ScrapeRequest.SerializeToString,
                response_deserializer=scrapper_dot_grpc_dot_scrapper__pb2.ScrapeResponse.FromString,
                _registered_method=True)


class ScrapperServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ScrapeNovels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScrapperServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScrapeNovels': grpc.unary_stream_rpc_method_handler(
                    servicer.ScrapeNovels,
                    request_deserializer=scrapper_dot_grpc_dot_scrapper__pb2.ScrapeRequest.FromString,
                    response_serializer=scrapper_dot_grpc_dot_scrapper__pb2.ScrapeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scrapper.ScrapperService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scrapper.ScrapperService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScrapperService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ScrapeNovels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scrapper.ScrapperService/ScrapeNovels',
            scrapper_dot_grpc_dot_scrapper__pb2.ScrapeRequest.SerializeToString,
            scrapper_dot_grpc_dot_scrapper__pb2.ScrapeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
