// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: updater.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UpdaterService_StartUpdate_FullMethodName   = "/updater.UpdaterService/StartUpdate"
	UpdaterService_StopUpdate_FullMethodName    = "/updater.UpdaterService/StopUpdate"
	UpdaterService_StreamUpdates_FullMethodName = "/updater.UpdaterService/StreamUpdates"
)

// UpdaterServiceClient is the client API for UpdaterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpdaterServiceClient interface {
	StartUpdate(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	StopUpdate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UpdateResponse, error)
	StreamUpdates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UpdateResponse], error)
}

type updaterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUpdaterServiceClient(cc grpc.ClientConnInterface) UpdaterServiceClient {
	return &updaterServiceClient{cc}
}

func (c *updaterServiceClient) StartUpdate(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, UpdaterService_StartUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updaterServiceClient) StopUpdate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, UpdaterService_StopUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updaterServiceClient) StreamUpdates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UpdateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UpdaterService_ServiceDesc.Streams[0], UpdaterService_StreamUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, UpdateResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UpdaterService_StreamUpdatesClient = grpc.ServerStreamingClient[UpdateResponse]

// UpdaterServiceServer is the server API for UpdaterService service.
// All implementations must embed UnimplementedUpdaterServiceServer
// for forward compatibility.
type UpdaterServiceServer interface {
	StartUpdate(context.Context, *UpdateRequest) (*UpdateResponse, error)
	StopUpdate(context.Context, *Empty) (*UpdateResponse, error)
	StreamUpdates(*Empty, grpc.ServerStreamingServer[UpdateResponse]) error
	mustEmbedUnimplementedUpdaterServiceServer()
}

// UnimplementedUpdaterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpdaterServiceServer struct{}

func (UnimplementedUpdaterServiceServer) StartUpdate(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartUpdate not implemented")
}
func (UnimplementedUpdaterServiceServer) StopUpdate(context.Context, *Empty) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopUpdate not implemented")
}
func (UnimplementedUpdaterServiceServer) StreamUpdates(*Empty, grpc.ServerStreamingServer[UpdateResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamUpdates not implemented")
}
func (UnimplementedUpdaterServiceServer) mustEmbedUnimplementedUpdaterServiceServer() {}
func (UnimplementedUpdaterServiceServer) testEmbeddedByValue()                        {}

// UnsafeUpdaterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpdaterServiceServer will
// result in compilation errors.
type UnsafeUpdaterServiceServer interface {
	mustEmbedUnimplementedUpdaterServiceServer()
}

func RegisterUpdaterServiceServer(s grpc.ServiceRegistrar, srv UpdaterServiceServer) {
	// If the following call pancis, it indicates UnimplementedUpdaterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UpdaterService_ServiceDesc, srv)
}

func _UpdaterService_StartUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdaterServiceServer).StartUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpdaterService_StartUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdaterServiceServer).StartUpdate(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UpdaterService_StopUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdaterServiceServer).StopUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpdaterService_StopUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdaterServiceServer).StopUpdate(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UpdaterService_StreamUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UpdaterServiceServer).StreamUpdates(m, &grpc.GenericServerStream[Empty, UpdateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UpdaterService_StreamUpdatesServer = grpc.ServerStreamingServer[UpdateResponse]

// UpdaterService_ServiceDesc is the grpc.ServiceDesc for UpdaterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpdaterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "updater.UpdaterService",
	HandlerType: (*UpdaterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartUpdate",
			Handler:    _UpdaterService_StartUpdate_Handler,
		},
		{
			MethodName: "StopUpdate",
			Handler:    _UpdaterService_StopUpdate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamUpdates",
			Handler:       _UpdaterService_StreamUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "updater.proto",
}
