// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: updater.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Input for starting/updating interval
type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntervalHours int32                  `protobuf:"varint,1,opt,name=interval_hours,json=intervalHours,proto3" json:"interval_hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_updater_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_updater_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_updater_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateRequest) GetIntervalHours() int32 {
	if x != nil {
		return x.IntervalHours
	}
	return 0
}

// Used for simple text messages or responses
type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_updater_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_updater_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_updater_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Generic empty message (no parameters)
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_updater_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_updater_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_updater_proto_rawDescGZIP(), []int{2}
}

var File_updater_proto protoreflect.FileDescriptor

const file_updater_proto_rawDesc = "" +
	"\n" +
	"\rupdater.proto\x12\aupdater\"6\n" +
	"\rUpdateRequest\x12%\n" +
	"\x0einterval_hours\x18\x01 \x01(\x05R\rintervalHours\"*\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\a\n" +
	"\x05Empty2\xc3\x01\n" +
	"\x0eUpdaterService\x12>\n" +
	"\vStartUpdate\x12\x16.updater.UpdateRequest\x1a\x17.updater.UpdateResponse\x125\n" +
	"\n" +
	"StopUpdate\x12\x0e.updater.Empty\x1a\x17.updater.UpdateResponse\x12:\n" +
	"\rStreamUpdates\x12\x0e.updater.Empty\x1a\x17.updater.UpdateResponse0\x01B\x03Z\x01.b\x06proto3"

var (
	file_updater_proto_rawDescOnce sync.Once
	file_updater_proto_rawDescData []byte
)

func file_updater_proto_rawDescGZIP() []byte {
	file_updater_proto_rawDescOnce.Do(func() {
		file_updater_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_updater_proto_rawDesc), len(file_updater_proto_rawDesc)))
	})
	return file_updater_proto_rawDescData
}

var file_updater_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_updater_proto_goTypes = []any{
	(*UpdateRequest)(nil),  // 0: updater.UpdateRequest
	(*UpdateResponse)(nil), // 1: updater.UpdateResponse
	(*Empty)(nil),          // 2: updater.Empty
}
var file_updater_proto_depIdxs = []int32{
	0, // 0: updater.UpdaterService.StartUpdate:input_type -> updater.UpdateRequest
	2, // 1: updater.UpdaterService.StopUpdate:input_type -> updater.Empty
	2, // 2: updater.UpdaterService.StreamUpdates:input_type -> updater.Empty
	1, // 3: updater.UpdaterService.StartUpdate:output_type -> updater.UpdateResponse
	1, // 4: updater.UpdaterService.StopUpdate:output_type -> updater.UpdateResponse
	1, // 5: updater.UpdaterService.StreamUpdates:output_type -> updater.UpdateResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_updater_proto_init() }
func file_updater_proto_init() {
	if File_updater_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_updater_proto_rawDesc), len(file_updater_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_updater_proto_goTypes,
		DependencyIndexes: file_updater_proto_depIdxs,
		MessageInfos:      file_updater_proto_msgTypes,
	}.Build()
	File_updater_proto = out.File
	file_updater_proto_goTypes = nil
	file_updater_proto_depIdxs = nil
}
