// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: genres.sql

package repositories

import (
	"context"
)

const addGenreToNovel = `-- name: AddGenreToNovel :exec
INSERT INTO novel_genres (novel_id, genre)
VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type AddGenreToNovelParams struct {
	NovelID int64
	Genre   string
}

func (q *Queries) AddGenreToNovel(ctx context.Context, arg AddGenreToNovelParams) error {
	_, err := q.db.ExecContext(ctx, addGenreToNovel, arg.NovelID, arg.Genre)
	return err
}

const deleteGenreFromNovel = `-- name: DeleteGenreFromNovel :exec
DELETE FROM novel_genres
WHERE novel_id = ? AND genre = ?
`

type DeleteGenreFromNovelParams struct {
	NovelID int64
	Genre   string
}

func (q *Queries) DeleteGenreFromNovel(ctx context.Context, arg DeleteGenreFromNovelParams) error {
	_, err := q.db.ExecContext(ctx, deleteGenreFromNovel, arg.NovelID, arg.Genre)
	return err
}

const listGenresByNovel = `-- name: ListGenresByNovel :many
SELECT genre FROM novel_genres
WHERE novel_id = ?
`

func (q *Queries) ListGenresByNovel(ctx context.Context, novelID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listGenresByNovel, novelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var genre string
		if err := rows.Scan(&genre); err != nil {
			return nil, err
		}
		items = append(items, genre)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
