// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repositories

type Chapter struct {
	ID            int64
	NovelID       int64
	ChapterNumber int64
	Title         string
	Content       string
}

type Novel struct {
	ID          int64
	Title       string
	Description string
	CoverImage  string
	Author      string
	Status      string
	UpdateTime  string
	ViewCount   int64
}

type NovelGenre struct {
	NovelID int64
	Genre   string
}

type NovelTag struct {
	NovelID int64
	Tag     string
}
