// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: novels.sql

package repositories

import (
	"context"
)

const countCompletedNovels = `-- name: CountCompletedNovels :one
SELECT COUNT(*) 
FROM novels
WHERE is_completed = 1
`

func (q *Queries) CountCompletedNovels(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCompletedNovels)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNovels = `-- name: CountNovels :one
SELECT COUNT(*) FROM novels
`

func (q *Queries) CountNovels(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNovels)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNovelsByAuthor = `-- name: CountNovelsByAuthor :one
SELECT COUNT(*)
FROM novels
WHERE author_slug = ? COLLATE NOCASE
`

func (q *Queries) CountNovelsByAuthor(ctx context.Context, authorSlug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNovelsByAuthor, authorSlug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOnGoingNovels = `-- name: CountOnGoingNovels :one
SELECT COUNT(*) 
FROM novels
WHERE is_completed = 0
`

func (q *Queries) CountOnGoingNovels(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOnGoingNovels)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchNovels = `-- name: CountSearchNovels :one
SELECT COUNT(*) AS total
FROM novels
WHERE LOWER(title) LIKE '%' || LOWER(?1) || '%'
`

func (q *Queries) CountSearchNovels(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchNovels, search)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createNovel = `-- name: CreateNovel :one
INSERT INTO novels (
    title, slug, description, cover_image, author, author_slug, publisher, release_year, is_completed, update_time, view_count
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0
)
RETURNING id, title, slug, description, cover_image, author, author_slug, publisher, release_year, is_completed, update_time, view_count
`

type CreateNovelParams struct {
	Title       string
	Slug        string
	Description string
	CoverImage  string
	Author      string
	AuthorSlug  string
	Publisher   string
	ReleaseYear int64
	IsCompleted int64
	UpdateTime  string
}

func (q *Queries) CreateNovel(ctx context.Context, arg CreateNovelParams) (Novel, error) {
	row := q.db.QueryRowContext(ctx, createNovel,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.CoverImage,
		arg.Author,
		arg.AuthorSlug,
		arg.Publisher,
		arg.ReleaseYear,
		arg.IsCompleted,
		arg.UpdateTime,
	)
	var i Novel
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverImage,
		&i.Author,
		&i.AuthorSlug,
		&i.Publisher,
		&i.ReleaseYear,
		&i.IsCompleted,
		&i.UpdateTime,
		&i.ViewCount,
	)
	return i, err
}

const deleteNovel = `-- name: DeleteNovel :exec
DELETE FROM novels WHERE id = ?
`

func (q *Queries) DeleteNovel(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNovel, id)
	return err
}

const getAuthorBySlug = `-- name: GetAuthorBySlug :one
SELECT DISTINCT author, author_slug
FROM novels
WHERE author_slug = ? COLLATE NOCASE
LIMIT 1
`

type GetAuthorBySlugRow struct {
	Author     string
	AuthorSlug string
}

func (q *Queries) GetAuthorBySlug(ctx context.Context, authorSlug string) (GetAuthorBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getAuthorBySlug, authorSlug)
	var i GetAuthorBySlugRow
	err := row.Scan(&i.Author, &i.AuthorSlug)
	return i, err
}

const getNovelByExactName = `-- name: GetNovelByExactName :one
SELECT id, title, slug, description, cover_image, author, author_slug, publisher, release_year, is_completed, update_time, view_count FROM novels
WHERE LOWER(title) = LOWER(?)
LIMIT 1
`

func (q *Queries) GetNovelByExactName(ctx context.Context, lower string) (Novel, error) {
	row := q.db.QueryRowContext(ctx, getNovelByExactName, lower)
	var i Novel
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverImage,
		&i.Author,
		&i.AuthorSlug,
		&i.Publisher,
		&i.ReleaseYear,
		&i.IsCompleted,
		&i.UpdateTime,
		&i.ViewCount,
	)
	return i, err
}

const getNovelByID = `-- name: GetNovelByID :one
SELECT id, title, slug, description, cover_image, author, author_slug, publisher, release_year, is_completed, update_time, view_count FROM novels
WHERE id = ? LIMIT 1
`

func (q *Queries) GetNovelByID(ctx context.Context, id int64) (Novel, error) {
	row := q.db.QueryRowContext(ctx, getNovelByID, id)
	var i Novel
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverImage,
		&i.Author,
		&i.AuthorSlug,
		&i.Publisher,
		&i.ReleaseYear,
		&i.IsCompleted,
		&i.UpdateTime,
		&i.ViewCount,
	)
	return i, err
}

const getNovelByNameLike = `-- name: GetNovelByNameLike :one
SELECT id, title, slug, description, cover_image, author, author_slug, publisher, release_year, is_completed, update_time, view_count FROM novels
WHERE LOWER(title) LIKE LOWER(?)
LIMIT 1
`

func (q *Queries) GetNovelByNameLike(ctx context.Context, lower string) (Novel, error) {
	row := q.db.QueryRowContext(ctx, getNovelByNameLike, lower)
	var i Novel
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverImage,
		&i.Author,
		&i.AuthorSlug,
		&i.Publisher,
		&i.ReleaseYear,
		&i.IsCompleted,
		&i.UpdateTime,
		&i.ViewCount,
	)
	return i, err
}

const getNovelBySlug = `-- name: GetNovelBySlug :one
SELECT id, title, slug, description, cover_image, author, author_slug, publisher, release_year, is_completed, update_time, view_count FROM novels
WHERE LOWER(slug) = LOWER(?)
LIMIT 1
`

func (q *Queries) GetNovelBySlug(ctx context.Context, lower string) (Novel, error) {
	row := q.db.QueryRowContext(ctx, getNovelBySlug, lower)
	var i Novel
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverImage,
		&i.Author,
		&i.AuthorSlug,
		&i.Publisher,
		&i.ReleaseYear,
		&i.IsCompleted,
		&i.UpdateTime,
		&i.ViewCount,
	)
	return i, err
}

const getNovelTags = `-- name: GetNovelTags :many
SELECT novel_id, tag, tag_slug
FROM novel_tags
WHERE novel_id = ?
`

func (q *Queries) GetNovelTags(ctx context.Context, novelID int64) ([]NovelTag, error) {
	rows, err := q.db.QueryContext(ctx, getNovelTags, novelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NovelTag
	for rows.Next() {
		var i NovelTag
		if err := rows.Scan(&i.NovelID, &i.Tag, &i.TagSlug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementNovelViewCount = `-- name: IncrementNovelViewCount :exec
UPDATE novels
SET view_count = view_count + 1,
    update_time = update_time
WHERE id = ?
`

func (q *Queries) IncrementNovelViewCount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementNovelViewCount, id)
	return err
}

const listCompletedNovels = `-- name: ListCompletedNovels :many
SELECT id, title, slug, description, cover_image, author, author_slug, publisher, release_year, is_completed, update_time, view_count
FROM novels
WHERE is_completed = 1
ORDER BY update_time DESC
`

func (q *Queries) ListCompletedNovels(ctx context.Context) ([]Novel, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedNovels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Novel
	for rows.Next() {
		var i Novel
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CoverImage,
			&i.Author,
			&i.AuthorSlug,
			&i.Publisher,
			&i.ReleaseYear,
			&i.IsCompleted,
			&i.UpdateTime,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedNovelsPaginated = `-- name: ListCompletedNovelsPaginated :many
SELECT id, title, slug, description, cover_image, author, author_slug, publisher, release_year, is_completed, update_time, view_count
FROM novels
WHERE is_completed = 1
ORDER BY update_time DESC
LIMIT ? OFFSET ?
`

type ListCompletedNovelsPaginatedParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListCompletedNovelsPaginated(ctx context.Context, arg ListCompletedNovelsPaginatedParams) ([]Novel, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedNovelsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Novel
	for rows.Next() {
		var i Novel
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CoverImage,
			&i.Author,
			&i.AuthorSlug,
			&i.Publisher,
			&i.ReleaseYear,
			&i.IsCompleted,
			&i.UpdateTime,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHotNovels = `-- name: ListHotNovels :many
SELECT id, title, slug, description, cover_image, author, author_slug, publisher, release_year, is_completed, update_time, view_count FROM novels
ORDER BY view_count DESC, update_time DESC
LIMIT 6
`

func (q *Queries) ListHotNovels(ctx context.Context) ([]Novel, error) {
	rows, err := q.db.QueryContext(ctx, listHotNovels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Novel
	for rows.Next() {
		var i Novel
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CoverImage,
			&i.Author,
			&i.AuthorSlug,
			&i.Publisher,
			&i.ReleaseYear,
			&i.IsCompleted,
			&i.UpdateTime,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHotNovelsPaginated = `-- name: ListHotNovelsPaginated :many
SELECT id, title, slug, description, cover_image, author, author_slug, publisher, release_year, is_completed, update_time, view_count
FROM novels
ORDER BY view_count DESC, update_time DESC
LIMIT ? OFFSET ?
`

type ListHotNovelsPaginatedParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListHotNovelsPaginated(ctx context.Context, arg ListHotNovelsPaginatedParams) ([]Novel, error) {
	rows, err := q.db.QueryContext(ctx, listHotNovelsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Novel
	for rows.Next() {
		var i Novel
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CoverImage,
			&i.Author,
			&i.AuthorSlug,
			&i.Publisher,
			&i.ReleaseYear,
			&i.IsCompleted,
			&i.UpdateTime,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewestHomeNovels = `-- name: ListNewestHomeNovels :many
SELECT id, title, slug, description, cover_image, author, author_slug, publisher, release_year, is_completed, update_time, view_count FROM novels
ORDER BY update_time DESC
LIMIT 6
`

func (q *Queries) ListNewestHomeNovels(ctx context.Context) ([]Novel, error) {
	rows, err := q.db.QueryContext(ctx, listNewestHomeNovels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Novel
	for rows.Next() {
		var i Novel
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CoverImage,
			&i.Author,
			&i.AuthorSlug,
			&i.Publisher,
			&i.ReleaseYear,
			&i.IsCompleted,
			&i.UpdateTime,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewestHomeNovelsPaginated = `-- name: ListNewestHomeNovelsPaginated :many
SELECT id, title, slug, description, cover_image, author, author_slug, publisher, release_year, is_completed, update_time, view_count
FROM novels
ORDER BY update_time DESC
LIMIT ? OFFSET ?
`

type ListNewestHomeNovelsPaginatedParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListNewestHomeNovelsPaginated(ctx context.Context, arg ListNewestHomeNovelsPaginatedParams) ([]Novel, error) {
	rows, err := q.db.QueryContext(ctx, listNewestHomeNovelsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Novel
	for rows.Next() {
		var i Novel
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CoverImage,
			&i.Author,
			&i.AuthorSlug,
			&i.Publisher,
			&i.ReleaseYear,
			&i.IsCompleted,
			&i.UpdateTime,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNovels = `-- name: ListNovels :many
SELECT id, title, slug, description, cover_image, author, author_slug, publisher, release_year, is_completed, update_time, view_count FROM novels
ORDER BY update_time DESC
`

func (q *Queries) ListNovels(ctx context.Context) ([]Novel, error) {
	rows, err := q.db.QueryContext(ctx, listNovels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Novel
	for rows.Next() {
		var i Novel
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CoverImage,
			&i.Author,
			&i.AuthorSlug,
			&i.Publisher,
			&i.ReleaseYear,
			&i.IsCompleted,
			&i.UpdateTime,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNovelsByAuthorPaginated = `-- name: ListNovelsByAuthorPaginated :many
SELECT id, title, slug, description, cover_image, author, author_slug, publisher, release_year, is_completed, update_time, view_count
FROM novels
WHERE author_slug = ? COLLATE NOCASE
ORDER BY update_time DESC
LIMIT ? OFFSET ?
`

type ListNovelsByAuthorPaginatedParams struct {
	AuthorSlug string
	Limit      int64
	Offset     int64
}

func (q *Queries) ListNovelsByAuthorPaginated(ctx context.Context, arg ListNovelsByAuthorPaginatedParams) ([]Novel, error) {
	rows, err := q.db.QueryContext(ctx, listNovelsByAuthorPaginated, arg.AuthorSlug, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Novel
	for rows.Next() {
		var i Novel
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CoverImage,
			&i.Author,
			&i.AuthorSlug,
			&i.Publisher,
			&i.ReleaseYear,
			&i.IsCompleted,
			&i.UpdateTime,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNovelsByChapterRange = `-- name: ListNovelsByChapterRange :many
SELECT n.id, n.title, n.slug, n.description, n.cover_image, n.author, n.author_slug, n.publisher, n.release_year, n.is_completed, n.update_time, n.view_count, 
       (SELECT COUNT(*) FROM chapters c WHERE c.novel_id = n.id) as chapter_count
FROM novels n
WHERE (SELECT COUNT(*) FROM chapters c WHERE c.novel_id = n.id) >= ?1 
  AND (SELECT COUNT(*) FROM chapters c WHERE c.novel_id = n.id) <= ?2
ORDER BY n.update_time DESC
`

type ListNovelsByChapterRangeParams struct {
	MinChapters int64
	MaxChapters int64
}

type ListNovelsByChapterRangeRow struct {
	ID           int64
	Title        string
	Slug         string
	Description  string
	CoverImage   string
	Author       string
	AuthorSlug   string
	Publisher    string
	ReleaseYear  int64
	IsCompleted  int64
	UpdateTime   string
	ViewCount    int64
	ChapterCount int64
}

func (q *Queries) ListNovelsByChapterRange(ctx context.Context, arg ListNovelsByChapterRangeParams) ([]ListNovelsByChapterRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, listNovelsByChapterRange, arg.MinChapters, arg.MaxChapters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNovelsByChapterRangeRow
	for rows.Next() {
		var i ListNovelsByChapterRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CoverImage,
			&i.Author,
			&i.AuthorSlug,
			&i.Publisher,
			&i.ReleaseYear,
			&i.IsCompleted,
			&i.UpdateTime,
			&i.ViewCount,
			&i.ChapterCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOnGoingNovelsPaginated = `-- name: ListOnGoingNovelsPaginated :many
SELECT id, title, slug, description, cover_image, author, author_slug, publisher, release_year, is_completed, update_time, view_count
FROM novels
WHERE is_completed = 0
ORDER BY update_time DESC
LIMIT ? OFFSET ?
`

type ListOnGoingNovelsPaginatedParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListOnGoingNovelsPaginated(ctx context.Context, arg ListOnGoingNovelsPaginatedParams) ([]Novel, error) {
	rows, err := q.db.QueryContext(ctx, listOnGoingNovelsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Novel
	for rows.Next() {
		var i Novel
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CoverImage,
			&i.Author,
			&i.AuthorSlug,
			&i.Publisher,
			&i.ReleaseYear,
			&i.IsCompleted,
			&i.UpdateTime,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNovels = `-- name: SearchNovels :many
SELECT id, title, slug, description, cover_image, author, author_slug, publisher, release_year, is_completed, update_time, view_count
FROM novels
WHERE LOWER(title) LIKE '%' || LOWER(?1) || '%'
ORDER BY update_time DESC
LIMIT ?3 OFFSET ?2
`

type SearchNovelsParams struct {
	Search string
	Offset int64
	Limit  int64
}

func (q *Queries) SearchNovels(ctx context.Context, arg SearchNovelsParams) ([]Novel, error) {
	rows, err := q.db.QueryContext(ctx, searchNovels, arg.Search, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Novel
	for rows.Next() {
		var i Novel
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CoverImage,
			&i.Author,
			&i.AuthorSlug,
			&i.Publisher,
			&i.ReleaseYear,
			&i.IsCompleted,
			&i.UpdateTime,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNovel = `-- name: UpdateNovel :one
UPDATE novels
SET
    title = ?,
    slug = ?,
    description = ?,
    cover_image = ?,
    author = ?,
    author_slug = ?,
    publisher = ?,
    release_year = ?,
    is_completed = ?,
    update_time = ?,
    view_count = ?
WHERE id = ?
RETURNING id, title, slug, description, cover_image, author, author_slug, publisher, release_year, is_completed, update_time, view_count
`

type UpdateNovelParams struct {
	Title       string
	Slug        string
	Description string
	CoverImage  string
	Author      string
	AuthorSlug  string
	Publisher   string
	ReleaseYear int64
	IsCompleted int64
	UpdateTime  string
	ViewCount   int64
	ID          int64
}

func (q *Queries) UpdateNovel(ctx context.Context, arg UpdateNovelParams) (Novel, error) {
	row := q.db.QueryRowContext(ctx, updateNovel,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.CoverImage,
		arg.Author,
		arg.AuthorSlug,
		arg.Publisher,
		arg.ReleaseYear,
		arg.IsCompleted,
		arg.UpdateTime,
		arg.ViewCount,
		arg.ID,
	)
	var i Novel
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverImage,
		&i.Author,
		&i.AuthorSlug,
		&i.Publisher,
		&i.ReleaseYear,
		&i.IsCompleted,
		&i.UpdateTime,
		&i.ViewCount,
	)
	return i, err
}

const updateNovelPartial = `-- name: UpdateNovelPartial :one
UPDATE novels
SET
    title = CASE WHEN ?1 IS NOT NULL THEN ?1 ELSE title END,
    slug = CASE WHEN ?2 IS NOT NULL THEN ?2 ELSE slug END,
    description = CASE WHEN ?3 IS NOT NULL THEN ?3 ELSE description END,
    cover_image = CASE WHEN ?4 IS NOT NULL THEN ?4 ELSE cover_image END,
    author = CASE WHEN ?5 IS NOT NULL THEN ?5 ELSE author END,
    author_slug = CASE WHEN ?6 IS NOT NULL THEN ?6 ELSE author_slug END,
    publisher = CASE WHEN ?7 IS NOT NULL THEN ?7 ELSE publisher END,
    release_year = CASE WHEN ?8 IS NOT NULL THEN ?8 ELSE release_year END,
    is_completed = CASE WHEN ?9 IS NOT NULL THEN ?9 ELSE is_completed END,
    update_time = CASE WHEN ?10 IS NOT NULL THEN ?10 ELSE update_time END,
    view_count = CASE WHEN ?11 IS NOT NULL THEN ?11 ELSE view_count END
WHERE id = ?12
RETURNING id, title, slug, description, cover_image, author, author_slug, publisher, release_year, is_completed, update_time, view_count
`

type UpdateNovelPartialParams struct {
	Title       interface{}
	Slug        interface{}
	Description interface{}
	CoverImage  interface{}
	Author      interface{}
	AuthorSlug  interface{}
	Publisher   interface{}
	ReleaseYear interface{}
	IsCompleted interface{}
	UpdateTime  interface{}
	ViewCount   interface{}
	ID          int64
}

func (q *Queries) UpdateNovelPartial(ctx context.Context, arg UpdateNovelPartialParams) (Novel, error) {
	row := q.db.QueryRowContext(ctx, updateNovelPartial,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.CoverImage,
		arg.Author,
		arg.AuthorSlug,
		arg.Publisher,
		arg.ReleaseYear,
		arg.IsCompleted,
		arg.UpdateTime,
		arg.ViewCount,
		arg.ID,
	)
	var i Novel
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverImage,
		&i.Author,
		&i.AuthorSlug,
		&i.Publisher,
		&i.ReleaseYear,
		&i.IsCompleted,
		&i.UpdateTime,
		&i.ViewCount,
	)
	return i, err
}
