# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scrapper/grpc_services/updater.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'scrapper/grpc_services/updater.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$scrapper/grpc_services/updater.proto\x12\x07updater\"\'\n\rUpdateRequest\x12\x16\n\x0einterval_hours\x18\x01 \x01(\x05\"!\n\x0eUpdateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xc3\x01\n\x0eUpdaterService\x12>\n\x0bStartUpdate\x12\x16.updater.UpdateRequest\x1a\x17.updater.UpdateResponse\x12\x35\n\nStopUpdate\x12\x0e.updater.Empty\x1a\x17.updater.UpdateResponse\x12:\n\rStreamUpdates\x12\x0e.updater.Empty\x1a\x17.updater.UpdateResponse0\x01\x42\x03Z\x01.b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scrapper.grpc_services.updater_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\001.'
  _globals['_UPDATEREQUEST']._serialized_start=49
  _globals['_UPDATEREQUEST']._serialized_end=88
  _globals['_UPDATERESPONSE']._serialized_start=90
  _globals['_UPDATERESPONSE']._serialized_end=123
  _globals['_EMPTY']._serialized_start=125
  _globals['_EMPTY']._serialized_end=132
  _globals['_UPDATERSERVICE']._serialized_start=135
  _globals['_UPDATERSERVICE']._serialized_end=330
# @@protoc_insertion_point(module_scope)
